version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: emissor_nfce_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emissor_nfce_1234
      POSTGRES_DB: emissor_nfce
    ports:
      - "9999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
